#!/usr/bin/env bash

build_bundles() {
    local script_dir repo_root bib_dir output_dir manifest bibclean awk_script bundle output style_file
    local combined unique stripped formatted source_file mapped_file style_input texnames bibnames
    local -a bib_files=() all_bib_files=()
    declare -A bundle_files seen_sources

    script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
    repo_root="$(cd -- "$script_dir/.." && pwd)"
    bib_dir="$repo_root/tex/bib"
    output_dir="$repo_root/inst/bib"
    style_file="$output_dir/journals-bibnames.sty"
    manifest="$script_dir/proposed-bibliography-bundles.md"
    bibclean="$script_dir/bibclean-2.17-windows/bibclean.exe"
    awk_script="$script_dir/bib-keys.awk"
    texnames="$script_dir/texnames.sty"
    bibnames="$script_dir/bibnames.sty"

    if [[ ! -x "$bibclean" ]]; then
        printf 'bibclean is not executable: %s\n' "$bibclean" >&2
        return 1
    fi
    if [[ ! -f "$awk_script" ]]; then
        printf 'Awk filter not found: %s\n' "$awk_script" >&2
        return 1
    fi
    if [[ ! -f "$manifest" ]]; then
        printf 'Bundle manifest not found: %s\n' "$manifest" >&2
        return 1
    fi
    if [[ ! -f "$texnames" || ! -f "$bibnames" ]]; then
        printf 'Bundled TeX macro source not found.\n' >&2
        return 1
    fi

    while IFS='|' read -r _ source_file mapped_file _ || [[ -n "$source_file" ]]; do
        source_file="${source_file//[[:space:]]/}"
        mapped_file="${mapped_file//[[:space:]]/}"
        [[ "$source_file" == *.bib && "$mapped_file" == *.bib ]] || continue

        if [[ -v "seen_sources[$source_file]" ]]; then
            printf 'Source file is mapped more than once: %s\n' "$source_file" >&2
            return 1
        fi
        if [[ ! -f "$bib_dir/$source_file" ]]; then
            printf 'Mapped source file not found: %s\n' "$bib_dir/$source_file" >&2
            return 1
        fi

        seen_sources["$source_file"]=1
        bundle_files["$mapped_file"]+="$bib_dir/$source_file"$'\n'
    done < "$manifest"

    if (( ${#bundle_files[@]} == 0 )); then
        printf 'No bibliography mappings found in %s\n' "$manifest" >&2
        return 1
    fi
    for source_file in "$bib_dir"/*.bib; do
        source_file="${source_file##*/}"
        if [[ ! -v "seen_sources[$source_file]" ]]; then
            printf 'Source file is not mapped: %s\n' "$source_file" >&2
            return 1
        fi
        all_bib_files+=("$bib_dir/$source_file")
    done

    mkdir -p -- "$output_dir"
    style_input="${style_file}.input.tmp"
    rm -f -- "$style_input" "$style_file"
    if ! "$bibclean" --max-width 0 "${all_bib_files[@]}" > "$style_input"; then
        printf 'bibclean failed; %s was not created.\n' "${style_file#$repo_root/}" >&2
        rm -f -- "$style_input"
        return 1
    fi
    {
        printf '%% Generated by software/build-fish_journals.sh.\n'
        printf '%% Includes public-domain sources from CTAN:\n'
        printf '%% https://mirrors.ctan.org/info/biblio/texnames.sty\n'
        printf '%% https://mirrors.ctan.org/info/biblio/bibnames.sty\n\n'
        cat "$texnames"
        printf '\n'
        cat "$bibnames"
        printf '\n'
    } > "$style_file"
    if ! awk '
        /^@Preamble[{]/ {
            preamble = $0
            sub(/^@Preamble[{]"/, "", preamble)
            sub(/"[}]$/, "", preamble)
            count = split(preamble, definitions, /" # "/)
            for (definition_index = 1; definition_index <= count; definition_index++) {
                definition = definitions[definition_index]
                if (definition == "\\input bibnames.sty" || definition in seen) {
                    continue
                }
                seen[definition] = 1
                print definition
            }
        }
    ' "$style_input" >> "$style_file"; then
        printf 'Preamble extraction failed; %s was not created.\n' "${style_file#$repo_root/}" >&2
        rm -f -- "$style_input" "$style_file"
        return 1
    fi
    rm -f -- "$style_input"
    printf 'Created %s.\n' "${style_file#$repo_root/}"

    while IFS= read -r bundle; do
        output="$output_dir/$bundle"
        combined="${output}.combined.tmp"
        unique="${output}.unique.tmp"
        stripped="${output}.stripped.tmp"
        formatted="${output}.formatted.tmp"
        mapfile -t bib_files <<< "${bundle_files[$bundle]}"

        rm -f -- "$combined" "$unique" "$stripped" "$formatted"
        if ! "$bibclean" --max-width 0 "${bib_files[@]}" > "$combined"; then
            printf 'bibclean failed; %s was not replaced.\n' "$bundle" >&2
            rm -f -- "$combined"
            return 1
        fi

        if ! awk -f "$awk_script" "$combined" > "$unique"; then
            printf 'Key generation failed; %s was not replaced.\n' "$bundle" >&2
            rm -f -- "$combined" "$unique"
            return 1
        fi

        if ! awk '
            /^%%% -\*-BibTeX-\*-/ {
                in_header = 1
                header_end = 0
                next
            }
            in_header {
                if ($0 ~ /^%%%  }/) {
                    header_end = 1
                } else if (header_end && $0 ~ /^%%% =+$/) {
                    in_header = 0
                }
                next
            }
            { print }
        ' "$unique" > "$stripped"; then
            printf 'Header removal failed; %s was not replaced.\n' "$bundle" >&2
            rm -f -- "$combined" "$unique" "$stripped"
            return 1
        fi

        if ! awk '
            /^@Preamble[{]/ {
                gsub(/ # /, " #\n    ")
            }
            { print }
        ' "$stripped" > "$formatted"; then
            printf 'Preamble formatting failed; %s was not replaced.\n' "$bundle" >&2
            rm -f -- "$combined" "$unique" "$stripped" "$formatted"
            return 1
        fi

        if ! "$bibclean" -no-prettyprint "$formatted" > /dev/null; then
            printf 'Generated bibliography is invalid; %s was not replaced.\n' "$bundle" >&2
            rm -f -- "$combined" "$unique" "$stripped" "$formatted"
            return 1
        fi

        mv -f -- "$formatted" "$output"
        rm -f -- "$combined" "$unique" "$stripped"
        printf 'Created %s from %d bibliography files.\n' "${output#$repo_root/}" "${#bib_files[@]}"
    done < <(printf '%s\n' "${!bundle_files[@]}" | sort)
}

build_bundles
build_status=$?
unset -f build_bundles
return "$build_status" 2>/dev/null || exit "$build_status"